### model
model_name_or_path: {ROOT_DIR}/models/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: identity, cot_vanilla
dataset_dir: {ROOT_DIR}/datasets/EmpatheticLLMs/PsyDTCorpus_train
template: qwen2.5
overwrite_cache: false
preprocessing_num_workers: 16

### output
output_dir: {ROOT_DIR}/checkpoint/EmpatheticLLMs/empathetic_sft_v1.0
logging_steps: 100
save_steps: 1000
plot_loss: true
overwrite_output_dir: false
save_total_limit: 2
load_best_model_at_end: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 20.0
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 12
eval_strategy: steps
eval_steps: 1000