### model
model_name_or_path: {ROOT_DIR}/models/Qwen2.5-7B-Instruct
adapter_name_or_path: {ROOT_DIR}/checkpoint/EmpatheticLLMs/empathetic_cot_v1.0
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: dpo_simulated
dataset_dir: {ROOT_DIR}/datasets/EmpatheticLLMs/PsyDTCorpus_train
template: qwen2.5
max_samples: 86000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: {ROOT_DIR}/checkpoint/EmpatheticLLMs/empathetic_dpo_v2.0
logging_steps: 100
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_total_limit: 2

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500