### model
model_name_or_path: /home/v-jiaswang/models/SoulChat2.0-Qwen2-7B

### method
finetuning_type: lora

### dataset
task: score-computation
dataset_name: train
dataset_dir: dataset/PsyDTCorpus_train
template: fewshot
lang: zh

### output
save_dir: dataset/PsyDTCorpus_score
overwrite_save_dir: true

### eval
batch_size: 8