### model
model_name_or_path: /home/v-jiaswang/models/Qwen2.5-7B-Instruct

### method
finetuning_type: freeze

### dataset
task: qwen_infer
dataset_name: PsyDTCorpus_test_single_turn_split
dataset_dir: ../dataset/PsyDTCorpus
template: qwen
lang: zh

### output
save_dir: dataset/PsyDTCorpus_test
overwrite_save_dir: true

### eval
batch_size: 8